
services:
  - type: web
    name: discord-oauth2-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: GUILD_ID
        sync: false
      - key: ROLE_ID
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
